### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by shoeper** [cbeneke/beneke.cc-content#1]
I came by your blog and searched for and RSS feed. It looks like there is none. Maybe you can add one. 

It looks like there is a plugin for grav https://github.com/getgrav/grav-plugin-feed

**Comment by cbeneke** [comment]
Hi, sorry for the long response time, this issue somehow slipped my attention.

I have the linked plugin installed in the blog since Aug 19, 2018 (compare https://github.com/cbeneke/grav-blog/commit/d4b9efffee2a6ae75c1521a21368150bf29075d6). You can find the feed at https://beneke.cc/blog.rss :)

Closing the issue here (and disabling issues, since this is repo is really just about hosting the content). If you have further questions please refer to the above linked repo. :)
